version: 2
jobs:

  build_code_develop:
    docker:
      - image: circleci/node:16.10.0

    working_directory: ~/Web-App
    steps:
      - checkout

      - restore_cache:
          keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
              - node_modules
      - run:
          name: Build React
          command: yarn run build
      # Cache the dist folder for the deploy job
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
              - build

  delete_code_develop:
    machine:
      enabled: true

    steps:
      - add_ssh_keys:
            fingerprints:
              - $SSH_HOST_FINGERPRINT_STAGING

      - run:
          name: SSH Remove User Front-end
          command: |
              ssh $SSH_USER_STAGING@$SSH_HOST_STAGING bash -c '
                rm -rf /var/www/add.xyz.v2/
                mkdir /var/www/add.xyz.v2/
                '


  deploy_code_develop:
    docker:
      - image: circleci/node:16.10.0
    working_directory: ~/Web-App
    user: ubuntu
    steps:
      - add_ssh_keys:
            fingerprints:
              - $SSH_HOST_FINGERPRINT_STAGING

      - restore_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: SSH SCP on Staging For Copy Build
          command: scp -o StrictHostKeyChecking=no -r ./build/* $SSH_USER_STAGING@$SSH_HOST_STAGING:/var/www/Web-App/

workflows:
  version: 2
  build_deploy_develop:
    jobs:
      - build_code_develop:
          filters:
            branches:
              only:
                - develop
      - delete_code_develop:
          filters:
            branches:
              only:
                - develop
          requires:
            - build_code_develop
      - deploy_code_develop:
          filters:
            branches:
              only:
                - develop
          requires:
            - delete_code_develop
